/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark_degemur_fernada2;

import org.junit.Test;

import spark.Spark;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }


public static void main(String[] args) {
    Spark.get("/welcome", (req, res) -> {
    return "Hallo DevOps";
    });
    }


    
    }
